### ISSUE TITLE
[discussion] jupyter lab support?

### ISSUE THREAD

**Issue by ddysher** [caicloud/ciao#28]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind feature
/priority p3

I'm not sure if jupyterlab has the same protocol with notebook (i hope they do).  Since the end goal of jupyterlab is to replace jupyter notebook, we'd better keep that in mind when designing the kernel.

**Comment by gaocegege** [comment]
Same, I can have a try.

**Comment by gaocegege** [comment]
Double checked, we support Lab.

**Comment by ddysher** [comment]
great
