### ISSUE TITLE
[feature] Cleanup after job is finished

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ciao#54]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

Delete all resources when a job is finished.

**Comment by gaocegege** [comment]
Kubeflow tfjob/pytorchjob now suports clean policy, thus we could just reuse it. Maybe we should add a new magic command to control the behavior. For exmaple

```
% cleanpolicy=All/Running/None
```

**Comment by yeya24** [comment]
@gaocegege  I' d like to take this. Look like not quite difficult for me. :smile:

**Comment by gaocegege** [comment]
@yeya24 I'd appreciate it if you could take this. Feel free to contact with me if you meet any question during the development!

/assign @yeya24 

(Maybe you cannot be assigned since you are not in the org, but it does not matter.)
